sharif_calendar_homepage:
    pattern:    /hello/{name}
    defaults:
        _controller:    SharifCalendarBundle:Default:index

sharif_calendar_calendar:
    pattern:    /user/calendar
    defaults:
        _controller:    SharifCalendarBundle:Events:calendar

sharif_calendar_edit_event:
    pattern:    /user/edit-event/{id}
    defaults:
        _controller:    SharifCalendarBundle:Events:editEvent

sharif_calendar_login:
    pattern:    /login
    defaults:
        _controller:    SharifCalendarBundle:UserManagement:login

sharif_calendar_login_check:
    pattern:    /secured_area/login_check

sharif_calendar_new_event:
    pattern:    /user/new_event
    defaults:
        _controller:    SharifCalendarBundle:Events:new

sharif_calendar_setting_labels:
    pattern:    /user/setting/labels
    defaults:
        _controller:    SharifCalendarBundle:UserManagement:settingLabels

sharif_calendar_signup:
    pattern:    /signup
    defaults:
        _controller:    SharifCalendarBundle:UserManagement:signup

sharif_calendar_signup_successful:
    pattern:    /signup_successful
    defaults:
        _controller:    FrameworkBundle:Template:template
        template:   'SharifCalendarBundle:UserManagement:signupSuccessful.html.twig'

sharif_calendar_submit_labels:
    pattern:    /user/submit/labels
    defaults:
        _controller:    SharifCalendarBundle:UserManagement:submitLabels
