security:

security:
    encoders:
        Sharif\CalendarBundle\Entity\User:
            algorithm:  sha1
            encode_as_base64:   false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        IS_AUTHENTICATED_OPENID:    ROLE_USER

    providers:
        openid_user_manager:
            id: sharif.calendar.openid_user_manager
        db:
            id: user_provider

    firewalls:
        main:
            pattern:    ^/
            fp_openid:
                create_user_if_not_exists: false
                login_path: sharif_calendar_login
                provider:   openid_user_manager
                remember_me:  true
                required_attributes:
                    - contact/email
            form_login:
                check_path: sharif_calendar_login_check
                login_path: sharif_calendar_login
                provider: db
                remember_me:  true
                username_parameter: _user
                password_parameter: _password
            remember_me:
                key:    "%secret%"
                lifetime:   31536000    # 365 days
                path:   /
                domain: ~   # Defaults to the current domain from $_SERVER
            logout: true
            anonymous:  true

    access_control:
        - { path: sharif_calendar_login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: sharif_calendar_signup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured_area, role: ROLE_USER }
