parameters:
#    sharif_calendar.example.class: Sharif\CalendarBundle\Example

services:
#    sharif_calendar.example:
#        class: %sharif_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
