services:
    sharif.calendar.openid_user_manager:
        class: Sharif\CalendarBundle\Security\OpenIdUserManager
        arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]

    user_provider:
        class: 'Sharif\CalendarBundle\Security\UserRepository'
        arguments:
            entityManager: '@doctrine.orm.entity_manager'

    sharif.calendar.date_manipulation_extension:
        class: Sharif\CalendarBundle\Twig\DateManipulationExtension
        tags:
            - { name: twig.extension }